=== AdrianRudametkin/DAM1_LDM/Examen1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="dadesfranquicia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="franquiciat"/>
        <xs:element ref="resultats"/>
        <xs:element name="tipusfranquicia" minOccurs="1"/>
        <xs:element ref="llistacomanda"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="franquiciat">
    <xs:complexType>
      <xs:all>
        <xs:element name="usuari" type="tipoUC"/>
        <xs:element name="contrasenya" type="tipoUC"/>
      </xs:all>
      <xs:attribute name="privilegi" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoUC">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="resultats">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="beneficinet" minOccurs="0" maxOccurs="1" default="0" >
          <xs:complexType mixed="true">
            <xs:attribute name="moneda" type="tipoMoneda"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="beneficibrut" minOccurs="1">
          <xs:complexType mixed="true">
            <xs:attribute name="moneda" type="tipoMoneda"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="inversio" minOccurs="1">
          <xs:complexType mixed="true">
            <xs:attribute name="moneda" type="tipoMoneda"/>          
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoBene">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tipoMoneda">
    <xs:restriction base="xs:string">
      <xs:enumeration value="euro"/>
      <xs:enumeration value="dolar"/>
      <xs:enumeration value="libras"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="tipusfranquicia">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[1-4]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="llistacomanda" id="id">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ampliable" type="xs:string"/>
        <xs:element ref="comanda" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comanda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producte">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[a-zA-z]{3,15} \d{0,4}[a-z]* \d"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" id="ID" use="required">
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdrianRudametkin/DAM1_LDM/Examen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dadesfranquicia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Examen1.xsd">
  <franquiciat privilegi="no">
    <usuari>pepet</usuari>
    <contrasenya>contra1</contrasenya>
  </franquiciat>
  <resultats>
      <beneficinet moneda="euro">300</beneficinet>
      <beneficibrut moneda="euro">800</beneficibrut>
      <inversio moneda="libras">500</inversio>
  </resultats>
  
  <tipusfranquicia>2</tipusfranquicia>

  <llistacomanda>
    <ampliable>TRUE</ampliable>
    <comanda id="1">
      <producte>fanta 33cl 5</producte>
    </comanda>
    <comanda id="2">
      <producte>colas 2lg 10</producte>
    </comanda>
    <comanda id="3">
      <producte>comidaperro 500g 20</producte>
    </comanda>  
  </llistacomanda>
</dadesfranquicia>
