=== AdrianRudametkin/DAM1_LDM/EjerciciosXSD/Ejercicio14.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="expresiones" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="expresion1"/>
              <xs:element ref="expresion2"/>
              <xs:element ref="expresion3"/>
              <xs:element ref="expresion4"/>
              <xs:element ref="expresion5"/>
              <xs:element ref="expresion6"/>
              <xs:element ref="expresion7"/>
              <xs:element ref="expresion8"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="expresion1">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="Capitulo \d"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion2">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="Capitulo \d*\d"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion3">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="Capitulo [1-9][0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion4">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="Capitulo \d{1,}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion5">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="\D[a-z|A-Z|?|=]*Z"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion6">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="AB{1,}C"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion7">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="RS{2,}\d*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="expresion8">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="COD\d\d\d.+"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== AdrianRudametkin/DAM1_LDM/Ejercicio14.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/alumno/Desktop/XML/Ejercicio14.xsd">
  <expresiones>
    <expresion1>Capitulo 0</expresion1>
    <expresion2>Capitulo 0</expresion2>
    <expresion3>Capitulo 1</expresion3>
    <expresion4>Capitulo 0</expresion4>
    <expresion5>aZ</expresion5>
    <expresion6>ABBC</expresion6>
    <expresion7>RSS</expresion7>
    <expresion8>COD645pera</expresion8>
  </expresiones>
  <expresiones>
    <expresion1>Capitulo 9</expresion1>
    <expresion2>Capitulo 99</expresion2>
    <expresion3>Capitulo 99</expresion3>
    <expresion4>Capitulo 99999</expresion4>
    <expresion5>?Z</expresion5>
    <expresion6>ABBBBBC</expresion6>
    <expresion7>RSSSSSSSSSSS7</expresion7>
    <expresion8>COD646manzana</expresion8>
 </expresiones>
</root>
